apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70


# kubectl autoscale deployment backend-deployment --cpu-percent=70 --min=1 --max=5
# requires Metrics server
# resource requests has to be defined in pods
# kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml 
# kubectl get --raw /apis/metrics.k8s.io/v1beta1
# kubectl get hpa backend-deployment --watch
# kubectl run -i --tty load-generator --rm --image=busybox --restart=Never -- /bin/sh -c "while sleep 0.001; do wget -q -O- http://backend:5000; done"
# kubectl run -i --tty load-generator --rm --image=artilleryio/artillery:1.6.2 --restart=Never -- quick -n 1000 -c 10 http://backend:5000