apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: c:\Utilities\shell-utils\kompose.exe convert -o ./k8s
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: c:\Utilities\shell-utils\kompose.exe convert -o ./k8s
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - image: frontend
          name: frontend
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
