apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: c:\Utilities\shell-utils\kompose.exe convert -o ./k8s
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: frontend
status:
  loadBalancer: {}
