apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
    tier: web
  annotations:
    owner: bartek
    color: blue
spec:
  containers:
    - name: nginx
      image: mcr.microsoft.com/oss/nginx/nginx:1.15.2-alpine
      ports:
      - containerPort: 80
      resources:
        requests:
          cpu: 250m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 256Mi


# kubectl get pods --selector=env=test