# create secret by cli
# kubectl create secret generic prod-db-secret --from-literal=username=db-user --from-literal=password=Y4nys7f11

apiVersion: v1
kind: Pod
metadata:
  name: secrets-test-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: prod-db-secret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: prod-db-secret
              key: password
  restartPolicy: Never
